---
name: Device Manager
version: 1.0.4
slug: device_manager
description: A web interface for the device manager
url: https://github.com/TISControlHass/TISDeviceManager
ingress: false
ingress_stream: false
panel_icon: mdi:database
arch:
  - aarch64
  - amd64
  - armv7
init: false
hassio_api: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  upload_limit: int?
ports:
  8000/tcp: 8000
